{{- if .Values.rbac.create -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "terranetes-controller.fullname" . }}-executor
rules:
  - apiGroups:
      - terraform.appvia.io
    resources:
      - contexts
    verbs:
      - create
      - get
      - list
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "terranetes-controller.fullname" . }}
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - list
  {{- if .Values.controller.registerCRDs }}
      - create
      - patch
      - update
  {{- end }}
  - apiGroups:
      - ""
      - batch
    resources:
      - configmaps
      - events
      - jobs
      - pods
      - secrets
    verbs:
      - create
      - delete
      - patch
      - update
  - apiGroups:
      - ""
      - batch
      - terraform.appvia.io
    resources:
      - cloudresources
      - configmaps
      - configurations
      - contexts
      - events
      - jobs
      - namespaces
      - plans
      - pods
      - policies
      - providers
      - revisions
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - terraform.appvia.io
    resources:
      - configurations
      - plans
      - plans/status
    verbs:
      - create
      - delete
  - apiGroups:
      - terraform.appvia.io
    resources:
      - configurations
      - configurations/status
      - contexts
      - contexts/status
      - cloudresources
      - cloudresources/status
      - plans
      - plans/status
      - policies
      - policies/status
      - providers
      - providers/status
      - revisions
      - revisions/status
    verbs:
      - patch
      - update
  - apiGroups:
      - admissionregistration.k8s.io
    resources:
      - mutatingwebhookconfigurations
      - validatingwebhookconfigurations
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "terranetes-controller.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "terranetes-controller.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: terranetes-controller
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "terranetes-controller.fullname" . }}-executor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "terranetes-controller.fullname" . }}-executor
subjects:
  {{- if .Values.rbac.enableExecutorServiceAccountPermissions }}
  - kind: Group
    name: system:serviceaccounts:{{ .Release.Namespace }}
    apiGroup: rbac.authorization.k8s.io
  {{- else }}
  - kind: ServiceAccount
    name: terranetes-executor
    namespace: {{ .Release.Namespace }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "terranetes-controller.fullname" . }}
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
      - delete
      - get
      - list
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
      - pods/log
    verbs:
      - create
      - delete
      - get
      - list
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "terranetes-controller.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "terranetes-controller.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: terranetes-controller
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "terranetes-controller.fullname" . }}-executor
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
      - delete
      - get
      - list
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: terranetes-executor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "terranetes-controller.fullname" . }}-executor
subjects:
  {{- if .Values.rbac.enableExecutorServiceAccountPermissions }}
  - kind: Group
    name: system:serviceaccounts:{{ .Release.Namespace }}
    apiGroup: rbac.authorization.k8s.io
  {{- else }}
  - kind: ServiceAccount
    name: terranetes-executor
    namespace: {{ .Release.Namespace }}
  {{- end }}
{{- end }}
