---
apiVersion: v2
name: terranetes-controller
description: Controller used to provision a terraform workflow within kubernetes
type: application
version: v0.4.8
appVersion: v0.3.18
sources:
  - https://github.com/appvia/terranetes-controller
  - https://github.com/appvia/terranetes
  - https://terranetes.appvia.io
maintainers:
  - name: Appvia
    email: info@appvia.io
    url: https://appvia.io
  - name: Rohith
    email: gambol99@gmail.com
    url: https://github.com/gambol99
