---
apiVersion: v2
name: terraform-controller
description: Controller used to provision a terraform workflow within kubernetes
type: application
version: v0.2.1
appVersion: v0.1.6
sources:
  - https://github.com/appvia/terraform-controller
  - https://github.com/appvia/terranetes
maintainers:
  - name: Appvia
    email: info@appvia.io
    url: https://appvia.io
